[package]
name = "parasolid-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
parasolid-core = { path = "../parasolid-core" }
pyo3.workspace = true

[lints]
workspace = true
